import type { HistoricalEvent } from "@chronodle/shared";

/**
 * Starter events loaded by `npm run db:seed`. Seeding skips ids that already
 * exist, so edits made in the admin are never overwritten. Add new events in
 * the admin rather than here.
 */
export const SEED_EVENTS: HistoricalEvent[] = [
  {
    id: "caesar-assassinated",
    name: "Caesar assassinated",
    description: "Julius Caesar is stabbed to death by senators in Rome on the Ides of March.",
    date: "-0044-03-15",
    wikipedia: "https://en.wikipedia.org/wiki/Assassination_of_Julius_Caesar",
    genre: "politics",
  },
  {
    id: "fall-of-western-rome",
    name: "Western Rome falls",
    description: "Odoacer deposes Romulus Augustulus, the last emperor of the Western Roman Empire.",
    date: "0476-09-04",
    wikipedia: "https://en.wikipedia.org/wiki/Fall_of_the_Western_Roman_Empire",
    genre: "politics",
  },
  {
    id: "charlemagne-crowned",
    name: "Charlemagne crowned",
    description: "Pope Leo III crowns Charlemagne Emperor of the Romans on Christmas Day.",
    date: "0800-12-25",
    wikipedia: "https://en.wikipedia.org/wiki/Coronation_of_Charlemagne",
    genre: "religion",
  },
  {
    id: "battle-of-hastings",
    name: "Battle of Hastings",
    description: "William of Normandy defeats King Harold II, beginning the Norman conquest of England.",
    date: "1066-10-14",
    wikipedia: "https://en.wikipedia.org/wiki/Battle_of_Hastings",
    genre: "war",
  },
  {
    id: "magna-carta",
    name: "Magna Carta sealed",
    description: "King John agrees to a charter limiting royal power at Runnymede.",
    date: "1215-06-15",
    wikipedia: "https://en.wikipedia.org/wiki/Magna_Carta",
    genre: "politics",
  },
  {
    id: "fall-of-constantinople",
    name: "Constantinople falls",
    description: "Ottoman forces under Mehmed II capture the Byzantine capital.",
    date: "1453-05-29",
    wikipedia: "https://en.wikipedia.org/wiki/Fall_of_Constantinople",
    genre: "war",
  },
  {
    id: "columbus-americas",
    name: "Columbus lands",
    description: "Christopher Columbus's expedition reaches an island in the Bahamas.",
    date: "1492-10-12",
    wikipedia: "https://en.wikipedia.org/wiki/Voyages_of_Christopher_Columbus",
    genre: "exploration",
  },
  {
    id: "ninety-five-theses",
    name: "Luther's 95 Theses",
    description: "Martin Luther circulates his challenge to the sale of indulgences in Wittenberg.",
    date: "1517-10-31",
    wikipedia: "https://en.wikipedia.org/wiki/Ninety-five_Theses",
    genre: "religion",
  },
  {
    id: "peace-of-westphalia",
    name: "Peace of Westphalia",
    description: "Treaties signed in Osnabrück and Münster end the Thirty Years' War.",
    date: "1648-10-24",
    wikipedia: "https://en.wikipedia.org/wiki/Peace_of_Westphalia",
    genre: "politics",
  },
  {
    id: "newton-principia",
    name: "Newton's Principia",
    description: "Isaac Newton publishes his laws of motion and universal gravitation.",
    date: "1687-07-05",
    wikipedia: "https://en.wikipedia.org/wiki/Philosophiæ_Naturalis_Principia_Mathematica",
    genre: "science",
  },
  {
    id: "us-independence",
    name: "US independence declared",
    description: "The Continental Congress adopts the Declaration of Independence.",
    date: "1776-07-04",
    wikipedia: "https://en.wikipedia.org/wiki/United_States_Declaration_of_Independence",
    genre: "politics",
  },
  {
    id: "storming-of-the-bastille",
    name: "Bastille stormed",
    description: "Parisian crowds seize the royal fortress-prison, a flashpoint of the French Revolution.",
    date: "1789-07-14",
    wikipedia: "https://en.wikipedia.org/wiki/Storming_of_the_Bastille",
    genre: "politics",
  },
  {
    id: "napoleon-crowned",
    name: "Napoleon crowned",
    description: "Napoleon Bonaparte crowns himself Emperor of the French at Notre-Dame.",
    date: "1804-12-02",
    wikipedia: "https://en.wikipedia.org/wiki/Coronation_of_Napoleon",
    genre: "politics",
  },
  {
    id: "battle-of-waterloo",
    name: "Battle of Waterloo",
    description: "Wellington and Blücher defeat Napoleon for the final time.",
    date: "1815-06-18",
    wikipedia: "https://en.wikipedia.org/wiki/Battle_of_Waterloo",
    genre: "war",
  },
  {
    id: "origin-of-species",
    name: "Origin of Species",
    description: "Charles Darwin publishes his theory of evolution by natural selection.",
    date: "1859-11-24",
    wikipedia: "https://en.wikipedia.org/wiki/On_the_Origin_of_Species",
    genre: "science",
  },
  {
    id: "emancipation-proclamation",
    name: "Emancipation Proclamation",
    description: "Abraham Lincoln declares enslaved people in Confederate states to be free.",
    date: "1863-01-01",
    wikipedia: "https://en.wikipedia.org/wiki/Emancipation_Proclamation",
    genre: "politics",
  },
  {
    id: "lincoln-assassinated",
    name: "Lincoln assassinated",
    description: "John Wilkes Booth shoots the president at Ford's Theatre in Washington.",
    date: "1865-04-14",
    wikipedia: "https://en.wikipedia.org/wiki/Assassination_of_Abraham_Lincoln",
    genre: "politics",
  },
  {
    id: "first-telephone-call",
    name: "First telephone call",
    description: "Alexander Graham Bell calls to his assistant: \"Mr. Watson, come here.\"",
    date: "1876-03-10",
    wikipedia: "https://en.wikipedia.org/wiki/Invention_of_the_telephone",
    genre: "technology",
  },
  {
    id: "first-modern-olympics",
    name: "First modern Olympics",
    description: "The revived Olympic Games open in Athens.",
    date: "1896-04-06",
    wikipedia: "https://en.wikipedia.org/wiki/1896_Summer_Olympics",
    genre: "culture",
  },
  {
    id: "wright-brothers-flight",
    name: "Wright brothers fly",
    description: "The first sustained, powered airplane flight lifts off at Kitty Hawk.",
    date: "1903-12-17",
    wikipedia: "https://en.wikipedia.org/wiki/Wright_Flyer",
    genre: "technology",
  },
  {
    id: "titanic-sinks",
    name: "Titanic sinks",
    description: "The 'unsinkable' liner goes down in the North Atlantic after striking an iceberg.",
    date: "1912-04-15",
    wikipedia: "https://en.wikipedia.org/wiki/Sinking_of_the_Titanic",
    genre: "disaster",
  },
  {
    id: "franz-ferdinand-assassinated",
    name: "Franz Ferdinand shot",
    description: "The Austro-Hungarian heir is assassinated in Sarajevo, setting off a world war.",
    date: "1914-06-28",
    wikipedia: "https://en.wikipedia.org/wiki/Assassination_of_Archduke_Franz_Ferdinand",
    genre: "war",
  },
  {
    id: "october-revolution",
    name: "October Revolution",
    description: "The Bolsheviks seize power in Petrograd.",
    date: "1917-11-07",
    wikipedia: "https://en.wikipedia.org/wiki/October_Revolution",
    genre: "politics",
  },
  {
    id: "wwi-armistice",
    name: "WWI armistice",
    description: "Fighting on the Western Front stops at the eleventh hour of the eleventh day.",
    date: "1918-11-11",
    wikipedia: "https://en.wikipedia.org/wiki/Armistice_of_11_November_1918",
    genre: "war",
  },
  {
    id: "lindbergh-transatlantic",
    name: "Lindbergh lands in Paris",
    description: "Charles Lindbergh completes the first solo nonstop flight across the Atlantic.",
    date: "1927-05-21",
    wikipedia: "https://en.wikipedia.org/wiki/Spirit_of_St._Louis",
    genre: "exploration",
  },
  {
    id: "penicillin-discovered",
    name: "Penicillin discovered",
    description: "Alexander Fleming notices mould killing bacteria in a forgotten petri dish.",
    date: "1928-09-28",
    wikipedia: "https://en.wikipedia.org/wiki/History_of_penicillin",
    genre: "science",
  },
  {
    id: "wall-street-crash",
    name: "Black Tuesday",
    description: "The Wall Street stock market crashes, deepening the Great Depression.",
    date: "1929-10-29",
    wikipedia: "https://en.wikipedia.org/wiki/Wall_Street_crash_of_1929",
    genre: "economy",
  },
  {
    id: "d-day",
    name: "D-Day landings",
    description: "Allied troops storm the beaches of Normandy.",
    date: "1944-06-06",
    wikipedia: "https://en.wikipedia.org/wiki/Normandy_landings",
    genre: "war",
  },
  {
    id: "hiroshima",
    name: "Hiroshima bombed",
    description: "The first atomic bomb used in war is dropped on a Japanese city.",
    date: "1945-08-06",
    wikipedia: "https://en.wikipedia.org/wiki/Atomic_bombings_of_Hiroshima_and_Nagasaki",
    genre: "war",
  },
  {
    id: "indian-independence",
    name: "Indian independence",
    description: "India becomes independent from British rule at midnight.",
    date: "1947-08-15",
    wikipedia: "https://en.wikipedia.org/wiki/Indian_Independence_Act_1947",
    genre: "politics",
  },
  {
    id: "sputnik",
    name: "Sputnik launched",
    description: "The Soviet Union puts the first artificial satellite into orbit.",
    date: "1957-10-04",
    wikipedia: "https://en.wikipedia.org/wiki/Sputnik_1",
    genre: "exploration",
  },
  {
    id: "jfk-assassinated",
    name: "JFK assassinated",
    description: "President John F. Kennedy is shot during a motorcade in Dallas.",
    date: "1963-11-22",
    wikipedia: "https://en.wikipedia.org/wiki/Assassination_of_John_F._Kennedy",
    genre: "politics",
  },
  {
    id: "moon-landing",
    name: "Moon landing",
    description: "Apollo 11's Neil Armstrong and Buzz Aldrin walk on the Moon.",
    date: "1969-07-20",
    wikipedia: "https://en.wikipedia.org/wiki/Apollo_11",
    genre: "exploration",
  },
  {
    id: "chernobyl",
    name: "Chernobyl disaster",
    description: "A reactor explodes at a nuclear power plant in Soviet Ukraine.",
    date: "1986-04-26",
    wikipedia: "https://en.wikipedia.org/wiki/Chernobyl_disaster",
    genre: "disaster",
  },
  {
    id: "berlin-wall-falls",
    name: "Berlin Wall falls",
    description: "East Germany opens the border and crowds begin tearing down the wall.",
    date: "1989-11-09",
    wikipedia: "https://en.wikipedia.org/wiki/Fall_of_the_Berlin_Wall",
    genre: "politics",
  },
  {
    id: "mandela-released",
    name: "Mandela released",
    description: "Nelson Mandela walks free after 27 years in prison.",
    date: "1990-02-11",
    wikipedia: "https://en.wikipedia.org/wiki/Nelson_Mandela",
    genre: "politics",
  },
  {
    id: "first-website",
    name: "First website online",
    description: "Tim Berners-Lee makes the World Wide Web available to the public.",
    date: "1991-08-06",
    wikipedia: "https://en.wikipedia.org/wiki/History_of_the_World_Wide_Web",
    genre: "technology",
  },
  {
    id: "september-11",
    name: "September 11 attacks",
    description: "Hijacked planes strike the World Trade Center and the Pentagon.",
    date: "2001-09-11",
    wikipedia: "https://en.wikipedia.org/wiki/September_11_attacks",
    genre: "disaster",
  },
  {
    id: "first-iphone",
    name: "iPhone goes on sale",
    description: "Apple's first smartphone reaches stores in the United States.",
    date: "2007-06-29",
    wikipedia: "https://en.wikipedia.org/wiki/IPhone_(1st_generation)",
    genre: "technology",
  },
];
